up:
	npm run dev

up.prod:
	npm run start:prod

build:
	npm run build

install:
	npm install

lint:
	npm run lint

lint.fix:
	npm run lint:fix

mock.api:
	docker compose up api-mock

output.api:
	redoc-cli bundle openapi.yaml --output outputs/api.html
