openapi: 3.0.4
info:
  title: TITLE API
  version: "1.0"
  description: MOCK API STRUCTURE
servers:
  - url: "http://localhost:3001/api"
paths:
  /auth/signin:
    post:
      tags: ["auth"]
      summary: sign in
      description: sign in
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: success
        401:
          description: Unauthorized
        500:
          description: internal server error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: user id
        email:
          type: string
          description: email
